# Generated by Django 6.0.2 on 2026-02-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_entry_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plaintext', 'Plain Text'), ('text/commommark', 'CommonMark'), ('image', 'Image')], default='text/plaintext', max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entries/'),
        ),
    ]
