# Generated by Django 6.0.2 on 2026-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_entry_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'CommonMark'), ('image', 'Image')], default='text/plaintext', max_length=20),
        ),
    ]
