# Generated by Django 6.0.2 on 2026-03-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_entry_github_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='github_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
