# Generated by Django 6.0.2 on 2026-03-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_hostedimage'),
        ('posts', '0009_alter_entry_github_event_id'),
    ]

    operations = [
    ]
