# Generated by Django 6.0.2 on 2026-03-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_merge_20260316_0340'),
        ('posts', '0010_merge_20260316_0503'),
    ]

    operations = [
    ]
