# Generated by Django 6.0.2 on 2026-03-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_merge_20260316_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends'), ('DELETED', 'Deleted')], db_index=True, default='PUBLIC', max_length=10),
        ),
    ]
