# Generated by Django 6.0.2 on 2026-03-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
        ('posts', '0012_alter_entry_published_at_alter_entry_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='remote_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_posts', to='accounts.author'),
        ),
    ]
