# Generated by Django 6.0.2 on 2026-03-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_entry_remote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
