# Generated by Django 6.0.2 on 2026-03-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_entry_fqid'), 
        ('posts', '0015_alter_entry_author'),
    ]

    operations = [
    ]
