# Generated by Django 6.0.2 on 2026-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_merge_0013_entry_fqid_0015_alter_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
