# Generated by Django 6.0.2 on 2026-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_entry_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
