# Generated by Django 6.0.2 on 2026-04-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_entry_image_url_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
