# Generated by Django 6.0.2 on 2026-03-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
        ('posts', '0003_entry_content_type_entry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.entry')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('author', 'entry')},
            },
        ),
    ]
