# Generated by Django 6.0.2 on 2026-03-02 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
        ('interactions', '0001_initial'),
        ('posts', '0003_entry_content_type_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.URLField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.entry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
