# Generated by Django 6.0.2 on 2026-03-02 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
        ('interactions', '0003_alter_like_id'),
        ('posts', '0003_entry_content_type_entry_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactions.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.entry'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'comment')},
        ),
    ]
