# Generated by Django 6.0.2 on 2026-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
        ('interactions', '0004_alter_like_unique_together_like_comment_and_more'),
        ('posts', '0010_merge_20260316_0503'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('entry__isnull', False)), fields=('author', 'entry'), name='unique_like_author_entry'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('author', 'comment'), name='unique_like_author_comment'),
        ),
    ]
