# Generated by Django 6.0.2 on 2026-03-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_fix_like_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='like',
            name='fqid',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
