# Generated by Django 6.0.2 on 2026-03-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_comment_fqid_like_fqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=50),
        ),
    ]
