# Generated by Django 6.0.2 on 2026-02-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
