# Generated by Django 6.0.2 on 2026-03-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_author_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImageUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
