# Generated by Django 6.0.2 on 2026-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Base URL of the remote node', max_length=255, unique=True)),
                ('username', models.CharField(help_text='Username for HTTP Basic Auth', max_length=150)),
                ('password', models.CharField(help_text='Password for HTTP Basic Auth', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this node can connect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remote Node',
                'verbose_name_plural': 'Remote Nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
